add plugin @routes-gen/solid-start
sandulat/routes-gen pull request #29
Opened 2022-12-30 22:15 UTC by nirtamir2

This PR adds a new plugin `@routes-gen/solid-start`.
It requires a patch for `solid-start` to expose `solid-start routes` command
If this change will be merged to solid - I will remove this part.
If the change is rejected (which is acceptable) - I need to do some patch packaging to solid-start somehow. I don't know which yarn version you use, and I will be happy to get help with patch packaging in yarn, or migrate to pnpm (and I will include the modified package of solid-start)
I inline test inside https://github.com/nirtamir2/solid-start-starter/tree/routes-gen but I haven't test a published package.

2022-12-30 22:15 UTC, nirtamir2 commented on package.json
> +    "postinstall": "patch-package",
All the patching can be removed once the patch will merge to solid-start

2022-12-30 22:16 UTC, nirtamir2 commented on packages/routes-gen-solid-start/package.json
> +    "patch-package": "^6.5.0",
All the patching can be removed once the patch will merge to solid-start

2022-12-30 22:17 UTC, nirtamir2 commented on packages/routes-gen-solid-start/src/index.ts
> +    exec(`node ${scriptPath} routes`, (error, stdout, stderr) => {
WDYT about this?
After I thought of modifying solid-start I notice they are not exposing `{cli}` like `@remix-run/dev`.
It's elegant - so I won't need to create a regex, but it requires node to run which is something I don't like.

2022-12-30 22:18 UTC, nirtamir2 commented on patches/solid-start+0.2.9.patch
> ++prog
This is the change I want to add to solid-start

2022-12-30 22:18 UTC, nirtamir2 commented on scripts/publish.js
> +  solidStartDriverJsonPath,
If we eventually use patch-package - we do not need this solid-start dep removal

2023-01-01 14:03 UTC, sandulat commented
@nirtamir2 answered in https://github.com/sandulat/routes-gen/discussions/28.

2023-01-03 22:03 UTC, nirtamir2 commented on packages/routes-gen-solid-start/src/index.ts
> +            const filteredRoutes = routes.filter((route) => {
As I see in the remix plugin - I filter the * paths.

2023-01-03 22:03 UTC, nirtamir2 commented on packages/routes-gen-solid-start/src/index.ts
> +      exec(`npx solid-start routes`, (error, stdout) => {
since v0.2.10 this is valid command

2023-01-03 22:04 UTC, nirtamir2 commented
@sandulat It's ready for review! 🎉

2023-01-08 13:51 UTC, sandulat commented
@nirtamir2 Sorry for the delay, I need to find some time to test it, since I've never used Solid/Solid Start before.

2023-01-08 13:59 UTC, nirtamir2 commented
@sandulat you can use https://github.com/nirtamir2/solid-start-starter/tree/routes-gen-published and replace my published package with the code you want, or just inline it like I've done in https://github.com/nirtamir2/solid-start-starter/tree/routes-gen

2023-01-16 22:34 UTC, nirtamir2 commented
@sandulat Any update? Can I help somehow?

2023-01-17 11:19 UTC, sandulat requested changes

2023-01-17 11:19 UTC, sandulat commented on packages/routes-gen-solid-start/README.md
> +yarn routes-gen -d @routes-gen/solud-start
yarn routes-gen -d @routes-gen/`solid`-start
Should be `solid` instead of `solud`

2023-01-17 11:19 UTC, sandulat commented on packages/routes-gen-solid-start/package.json
> +  }
Perhaps we should specify solid-start as a peer dependency?
```
  "peerDependencies": {
    "solid-start": "^0.2.10"
  }
  ```

2023-01-17 11:20 UTC, sandulat commented
@nirtamir2 At first glance, everything seems to be working. After doing the tiny fixes I've requested above, we can publish the package right away.

2023-01-17 11:48 UTC, nirtamir2 commented
@sandulat Thanks! I fixed the issues

2023-01-17 11:56 UTC, sandulat approved these changes

2023-01-17 11:57 UTC, merged

2023-01-17 12:04 UTC, sandulat commented
Thank you so much @nirtamir2! <3